/*
--------------
- Задание 1. -
--------------
*/
SELECT COALESCE(TABA.AUTHOR, TABB.AUTHOR) "Author",
	TABA.BIRTHDAY "Birthday",
	TABB.BOOK "Book"
FROM TABA
FULL JOIN TABB ON TABA.AUTHOR = TABB.AUTHOR
ORDER BY "Author",
	TABA.AUTHOR,
	TABB.BOOK;

/*
--------------
- Задание 2. -
--------------
*/
SELECT COALESCE(TABA.AUTHOR, TABB.AUTHOR) "Author",
	TABA.BIRTHDAY "Birthday",
	TABB.BOOK "Book"
FROM TABA
FULL JOIN TABB ON TABA.AUTHOR = TABB.AUTHOR
WHERE COALESCE(TABA.AUTHOR, TABB.AUTHOR) IN
		(SELECT AUTHOR
			FROM TABB
			GROUP BY AUTHOR
			HAVING COUNT(BOOK) > 1)
ORDER BY "Author",
	TABA.AUTHOR,
	TABB.BOOK;